TheCase2WebPortal/Controllers/SigortaliController.cs
using Entities.BUSINESS;
using Entities.CONFS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using TheCase2WebPortal.Helpers;
using TheCase2WebPortal.Models;
using TheCase2WebPortal.Models.Helpers;

namespace TheCase2WebPortal.Controllers
{
    public class SigortaliController : TheCase2WebPortalBaseController
    {
        private readonly IHttpClientFactoryService<List<sigortali>> _httpClientServiceImplementation;
        private readonly IHttpClientFactoryService<sigortali> _httpClientServiceImplementation2;
        private readonly IHttpClientFactoryService<object> _httpClientServiceImplementation3;
        public SigortaliController(
            ILogger<SigortaliController> Logger,
            IOptions<ApiSettings> ApiSettings,
            IOptions<JwtOptions> JwtOptions,
            IHttpClientFactoryService<List<sigortali>> HttpClientServiceImplementation,
            IHttpClientFactoryService<sigortali> HttpClientServiceImplementation2,
             IHttpClientFactoryService<object> HttpClientServiceImplementation3
            ) : base(Logger, ApiSettings, JwtOptions)
        {
            _httpClientServiceImplementation = HttpClientServiceImplementation;
            _httpClientServiceImplementation2 = HttpClientServiceImplementation2;
            _httpClientServiceImplementation3 = HttpClientServiceImplementation3;
        }
        public async Task<IActionResult> Liste()
        {
            var httpRequestRes = await _httpClientServiceImplementation.Execute(
               new RequestModel()
               {
                   BaseUrl = _apiSettings.BaseUrl,
                   Metod = "/sigortali/GetList",
                   RequestParam = string.Empty,
                   MetodType = HttpMethod.Get,
                   HeaderList = new Dictionary<string, string>() { { "Authorization", $"Bearer {User.FindFirst("AuthToken").Value}" } }

               });

            SigortaliViewModel sigortaliViewModel = new SigortaliViewModel()
            {
                SigortaliListesi = httpRequestRes.Data,
                Message = httpRequestRes.Message,
                Success = httpRequestRes.Success
            };
            return View(sigortaliViewModel);
        }
        public IActionResult Ekleme()
        {
            return View();
        }
        public async Task<IActionResult> Guncelleme(int id)
        {
            var httpRequestRes = await _httpClientServiceImplementation2.Execute(
                  new RequestModel()
                  {
                      BaseUrl = _apiSettings.BaseUrl,
                      Metod = "/sigortali/GetById",
                      RequestParam = $"id={id}",
                      MetodType = HttpMethod.Get,
                      HeaderList = new Dictionary<string, string>() { { "Authorization", $"Bearer {User.FindFirst("AuthToken").Value}" } }

                  });
            SigortaliViewModel sigortaliViewModel = new SigortaliViewModel()

            {
                sigortali = httpRequestRes.Data,
                Message = httpRequestRes.Message,
                Success = httpRequestRes.Success
            };
            return View(sigortaliViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Ekleme(SigortaliViewModel sigortaliViewModel)
        {
            var httpRequestRes = await _httpClientServiceImplementation3.Execute(
                 new RequestModel()
                 {
                     BaseUrl = _apiSettings.BaseUrl,
                     Metod = "/sigortali/Add",
                     RequestParam = JsonSerializer.Serialize(sigortaliViewModel.sigortali),
                     MetodType = HttpMethod.Post,
                     HeaderList = new Dictionary<string, string>() { { "Authorization", $"Bearer {User.FindFirst("AuthToken").Value}" } }

                 });



            if (httpRequestRes.Success)//gelen kayıt db ye başarılı kaydedilmiş ise listeme ekrananıa git
            {
                return RedirectToAction("Liste", "sigortali");
            }
            else
            {
                sigortaliViewModel.Message = httpRequestRes.Message;
                return View(sigortaliViewModel);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Guncelleme(SigortaliViewModel sigortaliViewModel)
        {
            var httpRequestRes = await _httpClientServiceImplementation3.Execute(
                new RequestModel()
                {
                    BaseUrl = _apiSettings.BaseUrl,
                    Metod = "/sigortali/Update",
                    RequestParam = JsonSerializer.Serialize(sigortaliViewModel.sigortali),
                    MetodType = HttpMethod.Post,
                    HeaderList = new Dictionary<string, string>() { { "Authorization", $"Bearer {User.FindFirst("AuthToken").Value}" } }

                });



            if (httpRequestRes.Success)//gelen kayıt db ye başarılı kaydedilmiş ise listeme ekrananıa git
            {
                return RedirectToAction("Liste", "sigortali");
            }
            else
            {
                sigortaliViewModel.Message = httpRequestRes.Message;
                return View(sigortaliViewModel);
            }
        }
    }
}

TheCase2WebPortal/Controllers/SozlesmeController.cs
using Entities.BUSINESS;
using Entities.CONFS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TheCase2WebPortal.Helpers;
using TheCase2WebPortal.Models;

namespace TheCase2WebPortal.Controllers
{
    public class SozlesmeController : TheCase2WebPortalBaseController
    {
        private readonly IHttpClientFactoryService<Police> _httpClientServiceImplementation;
        public SozlesmeController(
            ILogger<SozlesmeController> Logger,
            IOptions<ApiSettings> ApiSettings,
            IOptions<JwtOptions> JwtOptions
            ) : base(Logger, ApiSettings, JwtOptions)
        {
        }
        public IActionResult Liste()
        {
            return View();
        }
        public IActionResult Ekleme()
        {
            return View();
        }
        public IActionResult Guncelleme()
        {
            return View();
        }
    }
}

TheCase2WebPortal/Views/Shared/_LayoutBase.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Case2 Web Portal</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    @RenderBody()
</body>
</html>

TheCase2WebPortal/Views/Shared/_LayoutPageBase.cshtml
@{
    Layout = "_LayoutBase";
}
@section Styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <script src="Page.js"></script>
    @await RenderSectionAsync("PageStyles", required: false)
}
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <div class="text-center d-flex align-items-center justify-content-center">
                <a class="brand-logo" href="index.html"><img src="~/images/menu/logo-white.svg" alt="logo"></a>
                <a class="brand-logo-mini" href="index.html"><img src="~/images/menu/ts-icon.svg" alt="logo"></a>
            </div>
        </div>

        <ul class="list-unstyled components">
            <div class="user-profile">
                <div class="user-image">
                    <img src="~/images/profile/image0 (1).jpeg">
                </div>
                <div class="user-name">
                    ALI BORA ANZERLIOGLU
                </div>
                <div class="user-designation">
                    STAJYER
                </div>
            </div>
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Sözleşme</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a asp-controller="Sozlesme" asp-action="Liste">Liste</a>
                    </li>
                    <li>
                        <a asp-controller="Sozlesme" asp-action="Ekleme">Ekleme</a>
                    </li>
                    <li>
                        <a asp-controller="Sozlesme" asp-action="Guncelleme">Güncelleme</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#page1Submenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Poliçe</a>
                <ul class="collapse list-unstyled" id="page1Submenu">
                    <li>
                        <a asp-controller="Police" asp-action="Liste">Liste</a>
                    </li>
                    <li>
                        <a asp-controller="Police" asp-action="Ekleme">Ekleme</a>
                    </li>
                    <li>
                        <a asp-controller="Police" asp-action="Guncelleme">Güncelleme</a>
                    </li>
                </ul>
            </li>
            

            <li>
                <a href="#page2Submenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Person</a>
                <ul class="collapse list-unstyled" id="page2Submenu">
                    <li>
                        <a asp-controller="person" asp-action="Liste">Liste</a>
                    </li>
                    <li>
                        <a asp-controller="person" asp-action="Ekleme">Ekleme</a>
                    </li>
                    <li>
                        <a asp-controller="person" asp-action="Guncelleme">Güncelleme</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#page3Submenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Sigortali</a>
                <ul class="collapse list-unstyled" id="page3Submenu">
                    <li>
                        <a asp-controller="Sigortali" asp-action="Liste">Liste</a>
                    </li>
                    <li>
                        <a asp-controller="Sigortali" asp-action="Ekleme">Ekleme</a>
                    </li>
                    <li>
                        <a asp-controller="Sigortali" asp-action="Guncelleme">Güncelleme</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#page4Submenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Tarife</a>
                <ul class="collapse list-unstyled" id="page4Submenu">
                    <li>
                        <a asp-controller="Tarife" asp-action="Liste">Liste</a>
                    </li>
                    <li>
                        <a asp-controller="Tarife" asp-action="Ekleme">Ekleme</a>
                    </li>
                    <li>
                        <a asp-controller="Tarife" asp-action="Guncelleme">Güncelleme</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#page5Submenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Zeyl</a>
                <ul class="collapse list-unstyled" id="page5Submenu">
                    <li>
                        <a asp-controller="Zeyl" asp-action="Liste">Liste</a>
                    </li>
                    <li>
                        <a asp-controller="Zeyl" asp-action="Ekleme">Ekleme</a>
                    </li>
                    <li>
                        <a asp-controller="Zeyl" asp-action="Guncelleme">Güncelleme</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#page6Submenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Zeyltips</a>
                <ul class="collapse list-unstyled" id="page6Submenu">
                    <li>
                        <a asp-controller="Zeyltips" asp-action="Liste">Liste</a>
                    </li>
                    <li>
                        <a asp-controller="Zeyltips" asp-action="Ekleme">Ekleme</a>
                    </li>
                    <li>
                        <a asp-controller="Zeyltips" asp-action="Guncelleme">Güncelleme</a>
                    </li>
                </ul>
            </li>
            
            <li>
                <a href="#">Contact</a>
            </li>
        </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Login" asp-action="LogOut"><i class="fas fa-power-off"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @RenderBody()
        @section Scripts{
            <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js"></script>
            <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
            @await RenderSectionAsync("PageScripts", required: false)
        }
    </div>
</div>